# Generated by Django 4.2.3 on 2023-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='state',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
    ]
